# Form implementation generated from reading ui file 'lab3_gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 299)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.numbers_texbox = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.numbers_texbox.setGeometry(QtCore.QRect(100, 100, 281, 31))
        self.numbers_texbox.setObjectName("numbers_texbox")
        self.formula_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.formula_label.setGeometry(QtCore.QRect(40, 45, 61, 20))
        self.formula_label.setObjectName("formula_label")
        self.numbers_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.numbers_label.setGeometry(QtCore.QRect(40, 104, 61, 20))
        self.numbers_label.setObjectName("numbers_label")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(110, 190, 211, 61))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.done_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.done_button.setGeometry(QtCore.QRect(170, 140, 113, 32))
        self.done_button.setObjectName("done_button")
        self.formula_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.formula_box.setGeometry(QtCore.QRect(160, 40, 104, 26))
        self.formula_box.setObjectName("formula_box")
        self.formula_box.addItem("")
        self.formula_box.addItem("")
        self.formula_box.addItem("")
        self.formula_box.addItem("")
        self.formula_box.addItem("")
        self.formula_box.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FinalProject"))
        self.formula_label.setText(_translate("MainWindow", "Formula:"))
        self.numbers_label.setText(_translate("MainWindow", "Enter #s:"))
        self.done_button.setText(_translate("MainWindow", "Done"))
        self.formula_box.setItemText(0, _translate("MainWindow", "Random"))
        self.formula_box.setItemText(1, _translate("MainWindow", "Add"))
        self.formula_box.setItemText(2, _translate("MainWindow", "Subtract"))
        self.formula_box.setItemText(3, _translate("MainWindow", "Divide"))
        self.formula_box.setItemText(4, _translate("MainWindow", "Multiply"))
        self.formula_box.setItemText(5, _translate("MainWindow", "Square Root"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
